"""empty message

Revision ID: 826a1b45bd3d
Revises: 2b62fa08907a
Create Date: 2022-03-13 20:21:24.892801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826a1b45bd3d'
down_revision = '2b62fa08907a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
